/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecIndexRouteImport } from './routes/spec/index'
import { Route as NodesIndexRouteImport } from './routes/nodes/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as SpecTrustRouteImport } from './routes/spec/trust'
import { Route as SpecReasoningRouteImport } from './routes/spec/reasoning'
import { Route as SpecKnowledgeRouteImport } from './routes/spec/knowledge'
import { Route as SpecIdentityRouteImport } from './routes/spec/identity'
import { Route as SpecDiscoveryRouteImport } from './routes/spec/discovery'
import { Route as SpecCollaborationRouteImport } from './routes/spec/collaboration'
import { Route as NodesIdRouteImport } from './routes/nodes/$id'
import { Route as KnowledgeEntitiesRouteImport } from './routes/knowledge/entities'
import { Route as KnowledgeContributeRouteImport } from './routes/knowledge/contribute'
import { Route as BlogWhyInfrastructureRouteImport } from './routes/blog/why-infrastructure'
import { Route as BlogLaunchRouteImport } from './routes/blog/launch'
import { Route as NodesIdDashboardRouteImport } from './routes/nodes/$id/dashboard'
import { Route as KnowledgeEntitiesIdRouteImport } from './routes/knowledge/entities/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecIndexRoute = SpecIndexRouteImport.update({
  id: '/spec/',
  path: '/spec/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecTrustRoute = SpecTrustRouteImport.update({
  id: '/spec/trust',
  path: '/spec/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecReasoningRoute = SpecReasoningRouteImport.update({
  id: '/spec/reasoning',
  path: '/spec/reasoning',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecKnowledgeRoute = SpecKnowledgeRouteImport.update({
  id: '/spec/knowledge',
  path: '/spec/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecIdentityRoute = SpecIdentityRouteImport.update({
  id: '/spec/identity',
  path: '/spec/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecDiscoveryRoute = SpecDiscoveryRouteImport.update({
  id: '/spec/discovery',
  path: '/spec/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecCollaborationRoute = SpecCollaborationRouteImport.update({
  id: '/spec/collaboration',
  path: '/spec/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIdRoute = NodesIdRouteImport.update({
  id: '/nodes/$id',
  path: '/nodes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeEntitiesRoute = KnowledgeEntitiesRouteImport.update({
  id: '/knowledge/entities',
  path: '/knowledge/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeContributeRoute = KnowledgeContributeRouteImport.update({
  id: '/knowledge/contribute',
  path: '/knowledge/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhyInfrastructureRoute = BlogWhyInfrastructureRouteImport.update({
  id: '/blog/why-infrastructure',
  path: '/blog/why-infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLaunchRoute = BlogLaunchRouteImport.update({
  id: '/blog/launch',
  path: '/blog/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIdDashboardRoute = NodesIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => NodesIdRoute,
} as any)
const KnowledgeEntitiesIdRoute = KnowledgeEntitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KnowledgeEntitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/network': typeof NetworkRoute
  '/register': typeof RegisterRoute
  '/blog/launch': typeof BlogLaunchRoute
  '/blog/why-infrastructure': typeof BlogWhyInfrastructureRoute
  '/knowledge/contribute': typeof KnowledgeContributeRoute
  '/knowledge/entities': typeof KnowledgeEntitiesRouteWithChildren
  '/nodes/$id': typeof NodesIdRouteWithChildren
  '/spec/collaboration': typeof SpecCollaborationRoute
  '/spec/discovery': typeof SpecDiscoveryRoute
  '/spec/identity': typeof SpecIdentityRoute
  '/spec/knowledge': typeof SpecKnowledgeRoute
  '/spec/reasoning': typeof SpecReasoningRoute
  '/spec/trust': typeof SpecTrustRoute
  '/blog/': typeof BlogIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/spec/': typeof SpecIndexRoute
  '/knowledge/entities/$id': typeof KnowledgeEntitiesIdRoute
  '/nodes/$id/dashboard': typeof NodesIdDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/network': typeof NetworkRoute
  '/register': typeof RegisterRoute
  '/blog/launch': typeof BlogLaunchRoute
  '/blog/why-infrastructure': typeof BlogWhyInfrastructureRoute
  '/knowledge/contribute': typeof KnowledgeContributeRoute
  '/knowledge/entities': typeof KnowledgeEntitiesRouteWithChildren
  '/nodes/$id': typeof NodesIdRouteWithChildren
  '/spec/collaboration': typeof SpecCollaborationRoute
  '/spec/discovery': typeof SpecDiscoveryRoute
  '/spec/identity': typeof SpecIdentityRoute
  '/spec/knowledge': typeof SpecKnowledgeRoute
  '/spec/reasoning': typeof SpecReasoningRoute
  '/spec/trust': typeof SpecTrustRoute
  '/blog': typeof BlogIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/nodes': typeof NodesIndexRoute
  '/spec': typeof SpecIndexRoute
  '/knowledge/entities/$id': typeof KnowledgeEntitiesIdRoute
  '/nodes/$id/dashboard': typeof NodesIdDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/network': typeof NetworkRoute
  '/register': typeof RegisterRoute
  '/blog/launch': typeof BlogLaunchRoute
  '/blog/why-infrastructure': typeof BlogWhyInfrastructureRoute
  '/knowledge/contribute': typeof KnowledgeContributeRoute
  '/knowledge/entities': typeof KnowledgeEntitiesRouteWithChildren
  '/nodes/$id': typeof NodesIdRouteWithChildren
  '/spec/collaboration': typeof SpecCollaborationRoute
  '/spec/discovery': typeof SpecDiscoveryRoute
  '/spec/identity': typeof SpecIdentityRoute
  '/spec/knowledge': typeof SpecKnowledgeRoute
  '/spec/reasoning': typeof SpecReasoningRoute
  '/spec/trust': typeof SpecTrustRoute
  '/blog/': typeof BlogIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/spec/': typeof SpecIndexRoute
  '/knowledge/entities/$id': typeof KnowledgeEntitiesIdRoute
  '/nodes/$id/dashboard': typeof NodesIdDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/discover'
    | '/docs'
    | '/network'
    | '/register'
    | '/blog/launch'
    | '/blog/why-infrastructure'
    | '/knowledge/contribute'
    | '/knowledge/entities'
    | '/nodes/$id'
    | '/spec/collaboration'
    | '/spec/discovery'
    | '/spec/identity'
    | '/spec/knowledge'
    | '/spec/reasoning'
    | '/spec/trust'
    | '/blog/'
    | '/knowledge/'
    | '/nodes/'
    | '/spec/'
    | '/knowledge/entities/$id'
    | '/nodes/$id/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/discover'
    | '/docs'
    | '/network'
    | '/register'
    | '/blog/launch'
    | '/blog/why-infrastructure'
    | '/knowledge/contribute'
    | '/knowledge/entities'
    | '/nodes/$id'
    | '/spec/collaboration'
    | '/spec/discovery'
    | '/spec/identity'
    | '/spec/knowledge'
    | '/spec/reasoning'
    | '/spec/trust'
    | '/blog'
    | '/knowledge'
    | '/nodes'
    | '/spec'
    | '/knowledge/entities/$id'
    | '/nodes/$id/dashboard'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/discover'
    | '/docs'
    | '/network'
    | '/register'
    | '/blog/launch'
    | '/blog/why-infrastructure'
    | '/knowledge/contribute'
    | '/knowledge/entities'
    | '/nodes/$id'
    | '/spec/collaboration'
    | '/spec/discovery'
    | '/spec/identity'
    | '/spec/knowledge'
    | '/spec/reasoning'
    | '/spec/trust'
    | '/blog/'
    | '/knowledge/'
    | '/nodes/'
    | '/spec/'
    | '/knowledge/entities/$id'
    | '/nodes/$id/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  DiscoverRoute: typeof DiscoverRoute
  DocsRoute: typeof DocsRoute
  NetworkRoute: typeof NetworkRoute
  RegisterRoute: typeof RegisterRoute
  BlogLaunchRoute: typeof BlogLaunchRoute
  BlogWhyInfrastructureRoute: typeof BlogWhyInfrastructureRoute
  KnowledgeContributeRoute: typeof KnowledgeContributeRoute
  KnowledgeEntitiesRoute: typeof KnowledgeEntitiesRouteWithChildren
  NodesIdRoute: typeof NodesIdRouteWithChildren
  SpecCollaborationRoute: typeof SpecCollaborationRoute
  SpecDiscoveryRoute: typeof SpecDiscoveryRoute
  SpecIdentityRoute: typeof SpecIdentityRoute
  SpecKnowledgeRoute: typeof SpecKnowledgeRoute
  SpecReasoningRoute: typeof SpecReasoningRoute
  SpecTrustRoute: typeof SpecTrustRoute
  BlogIndexRoute: typeof BlogIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  NodesIndexRoute: typeof NodesIndexRoute
  SpecIndexRoute: typeof SpecIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec/': {
      id: '/spec/'
      path: '/spec'
      fullPath: '/spec/'
      preLoaderRoute: typeof SpecIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec/trust': {
      id: '/spec/trust'
      path: '/spec/trust'
      fullPath: '/spec/trust'
      preLoaderRoute: typeof SpecTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec/reasoning': {
      id: '/spec/reasoning'
      path: '/spec/reasoning'
      fullPath: '/spec/reasoning'
      preLoaderRoute: typeof SpecReasoningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec/knowledge': {
      id: '/spec/knowledge'
      path: '/spec/knowledge'
      fullPath: '/spec/knowledge'
      preLoaderRoute: typeof SpecKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec/identity': {
      id: '/spec/identity'
      path: '/spec/identity'
      fullPath: '/spec/identity'
      preLoaderRoute: typeof SpecIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec/discovery': {
      id: '/spec/discovery'
      path: '/spec/discovery'
      fullPath: '/spec/discovery'
      preLoaderRoute: typeof SpecDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec/collaboration': {
      id: '/spec/collaboration'
      path: '/spec/collaboration'
      fullPath: '/spec/collaboration'
      preLoaderRoute: typeof SpecCollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$id': {
      id: '/nodes/$id'
      path: '/nodes/$id'
      fullPath: '/nodes/$id'
      preLoaderRoute: typeof NodesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/entities': {
      id: '/knowledge/entities'
      path: '/knowledge/entities'
      fullPath: '/knowledge/entities'
      preLoaderRoute: typeof KnowledgeEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/contribute': {
      id: '/knowledge/contribute'
      path: '/knowledge/contribute'
      fullPath: '/knowledge/contribute'
      preLoaderRoute: typeof KnowledgeContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/why-infrastructure': {
      id: '/blog/why-infrastructure'
      path: '/blog/why-infrastructure'
      fullPath: '/blog/why-infrastructure'
      preLoaderRoute: typeof BlogWhyInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/launch': {
      id: '/blog/launch'
      path: '/blog/launch'
      fullPath: '/blog/launch'
      preLoaderRoute: typeof BlogLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$id/dashboard': {
      id: '/nodes/$id/dashboard'
      path: '/dashboard'
      fullPath: '/nodes/$id/dashboard'
      preLoaderRoute: typeof NodesIdDashboardRouteImport
      parentRoute: typeof NodesIdRoute
    }
    '/knowledge/entities/$id': {
      id: '/knowledge/entities/$id'
      path: '/$id'
      fullPath: '/knowledge/entities/$id'
      preLoaderRoute: typeof KnowledgeEntitiesIdRouteImport
      parentRoute: typeof KnowledgeEntitiesRoute
    }
  }
}

interface KnowledgeEntitiesRouteChildren {
  KnowledgeEntitiesIdRoute: typeof KnowledgeEntitiesIdRoute
}

const KnowledgeEntitiesRouteChildren: KnowledgeEntitiesRouteChildren = {
  KnowledgeEntitiesIdRoute: KnowledgeEntitiesIdRoute,
}

const KnowledgeEntitiesRouteWithChildren =
  KnowledgeEntitiesRoute._addFileChildren(KnowledgeEntitiesRouteChildren)

interface NodesIdRouteChildren {
  NodesIdDashboardRoute: typeof NodesIdDashboardRoute
}

const NodesIdRouteChildren: NodesIdRouteChildren = {
  NodesIdDashboardRoute: NodesIdDashboardRoute,
}

const NodesIdRouteWithChildren =
  NodesIdRoute._addFileChildren(NodesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  DiscoverRoute: DiscoverRoute,
  DocsRoute: DocsRoute,
  NetworkRoute: NetworkRoute,
  RegisterRoute: RegisterRoute,
  BlogLaunchRoute: BlogLaunchRoute,
  BlogWhyInfrastructureRoute: BlogWhyInfrastructureRoute,
  KnowledgeContributeRoute: KnowledgeContributeRoute,
  KnowledgeEntitiesRoute: KnowledgeEntitiesRouteWithChildren,
  NodesIdRoute: NodesIdRouteWithChildren,
  SpecCollaborationRoute: SpecCollaborationRoute,
  SpecDiscoveryRoute: SpecDiscoveryRoute,
  SpecIdentityRoute: SpecIdentityRoute,
  SpecKnowledgeRoute: SpecKnowledgeRoute,
  SpecReasoningRoute: SpecReasoningRoute,
  SpecTrustRoute: SpecTrustRoute,
  BlogIndexRoute: BlogIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  NodesIndexRoute: NodesIndexRoute,
  SpecIndexRoute: SpecIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
